server:
  port: 8083

spring:
  application:
    name: banking-app
  datasource:
    url: jdbc:mysql://localhost:3306/banking_app
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update